# Generated by Django 4.2.1 on 2023-05-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_D', models.CharField(choices=[(' Réparation', ' Réparation'), ('Attribution', 'Attribution')], max_length=200, null=True)),
                ('type', models.CharField(choices=[(' Réparation', ' Réparation'), ('Attribution', 'Attribution')], max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statuts', models.CharField(choices=[(' traitée', ' traitée'), ('en cours', 'non cours'), ('remis', 'remis')], max_length=200, null=True)),
            ],
        ),
    ]
