# Generated by Django 4.2.1 on 2023-05-21 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0001_initial'),
        ('employe', '0001_initial'),
        ('demande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employe.employe'),
        ),
        migrations.AddField(
            model_name='demande',
            name='materiel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiel.materiel'),
        ),
    ]
