# Generated by Django 4.2.1 on 2023-05-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0002_demande_employe_demande_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='ID_D',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
