# Generated by Django 4.2.1 on 2023-05-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0003_alter_demande_id_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
