# Generated by Django 4.2.1 on 2023-05-31 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0002_alter_technicien_id_t'),
        ('demande', '0008_alter_demande_statuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='technicien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technicien.technicien'),
        ),
    ]
