# Generated by Django 4.2.1 on 2023-05-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0009_demande_technicien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='technicien',
        ),
    ]
