# Generated by Django 4.2.1 on 2023-06-01 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0003_technicien_demandes_assignees'),
        ('demande', '0012_remove_demande_technicien'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='technicien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technicien.technicien'),
        ),
    ]
