# Generated by Django 4.2.1 on 2023-06-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0005_technicien_demandes_assignees'),
        ('demande', '0015_alter_demande_technicien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technicien.technicien'),
        ),
    ]
