# Generated by Django 4.2.1 on 2023-06-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0016_alter_demande_technicien'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='demandes_assignees',
            field=models.ManyToManyField(blank=True, related_name='assignees', to='demande.demande'),
        ),
    ]
