# Generated by Django 4.2.1 on 2023-06-03 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0009_remove_materiel_nom_m_remove_materiel_qte_enstock'),
        ('demande', '0020_demande_demandes_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='demandes_assignees',
        ),
        migrations.AlterField(
            model_name='demande',
            name='materiel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiel.materiel'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statuts',
            field=models.CharField(choices=[('traitée', 'Traitée'), ('en cours', 'En cours'), ('non traitée', 'Non traitée')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='type',
            field=models.CharField(choices=[('Réparation', 'Réparation'), ('Attribution', 'Attribution')], max_length=200, null=True),
        ),
    ]
