# Generated by Django 4.2.1 on 2023-06-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0021_remove_demande_demandes_assignees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statuts',
            field=models.CharField(choices=[(' traitée', ' traitée'), ('en cours', 'en cours'), ('non traitée', 'non traitée')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='type',
            field=models.CharField(choices=[(' Réparation', ' Réparation'), ('Attribution', 'Attribution')], max_length=200, null=True),
        ),
    ]
