# Generated by Django 4.2.1 on 2023-06-03 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_alter_employe_id_e'),
        ('demande', '0022_alter_demande_statuts_alter_demande_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employe.employe'),
        ),
    ]
