# Generated by Django 4.2.1 on 2023-05-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_T', models.CharField(max_length=200, null=True)),
                ('statuts', models.CharField(choices=[('Assigné', 'Assigné'), ('Libre', 'Libre')], max_length=200, null=True)),
                ('Nom', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
