# Generated by Django 4.2.1 on 2023-05-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicien',
            name='ID_T',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
