# Generated by Django 4.2.1 on 2023-05-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0011_demande_technicien'),
        ('technicien', '0002_alter_technicien_id_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='demandes_assignees',
            field=models.ManyToManyField(related_name='techniciens_assignes', to='demande.demande'),
        ),
    ]
