# Generated by Django 4.2.1 on 2023-06-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0014_alter_demande_technicien'),
        ('technicien', '0004_remove_technicien_demandes_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='demandes_assignees',
            field=models.ManyToManyField(blank=True, related_name='techniciens_assignes', to='demande.demande'),
        ),
    ]
