# Generated by Django 4.2.1 on 2023-05-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_E', models.CharField(max_length=200, null=True)),
                ('nomE', models.CharField(max_length=200, null=True)),
                ('departement', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
