# Generated by Django 4.2.1 on 2023-05-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_remove_employe_s_employe_departement_delete_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='ID_E',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
