# Generated by Django 4.2.1 on 2023-06-23 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_alter_employe_id_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='date_ajout',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
