# Generated by Django 4.2.1 on 2023-05-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0002_alter_materiel_datedereception'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='departement_m',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
