# Generated by Django 4.2.1 on 2023-05-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0003_materiel_departement_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='departement_m',
        ),
    ]
