# Generated by Django 4.2.1 on 2023-05-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0004_remove_materiel_departement_m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiel',
            old_name='tag',
            new_name='departement_m',
        ),
    ]
