# Generated by Django 4.2.1 on 2023-05-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0006_alter_materiel_id_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='qte_enstock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
