# Generated by Django 4.2.1 on 2023-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0007_materiel_qte_enstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='Nom_M',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
