# Generated by Django 4.2.1 on 2023-05-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0008_materiel_nom_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='Nom_M',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='qte_enstock',
        ),
    ]
