# Generated by Django 4.2.1 on 2023-07-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0009_remove_materiel_nom_m_remove_materiel_qte_enstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiel',
            old_name='departement_m',
            new_name='departement',
        ),
    ]
